### PR TITLE
Fix false positives in diagnostics

### LINKED ISSUE #270: "Type aliases are only allowed in typescript"
### Initial checklist

- [X] I read the [support docs](https://mdxjs.com/community/support/)
- [X] I read the [contributing guide](https://mdxjs.com/community/contribute/)
- [X] I agree to follow the [code of conduct](https://github.com/mdx-js/.github/blob/HEAD/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amdx-js&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.1.0

### Link to runnable example

_No response_

### Steps to reproduce

running w/ the experimental language server enabled, node 18

image

If I open a typescript file and write typescript code, it errors at me.
I determined it was this extension through extension bisect.

### Expected behavior

typescript code works in files named `.ts` and `.tsx`, and MDX doesn't complain about it

### Actual behavior

see above screenshot

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm v8

### OS

macOS

### Build and bundle tools

Vite

### PR DESCRIPTION
**Pull request by remcohaszing**
This fixes two issues, which together triggered invalid diagnostics in JSX and TypeScript files.

1. The language service treated all non-MDX files as JavaScript.
2. The language server emitted diagnostics for non-MDX files, causing the invalid diagnostics to bubble up to the user, and causing more diagnostics to be duplicated if TypeScript was enabled.

Closes #270

### CODE REVIEW

File: packages/language-server/index.js [hunk 1]
```diff
@@ -316,6 +317,11 @@ documents.onDidClose((event) => {
  */
 async function checkDiagnostics(event) {
   const {uri} = event.document
+
+  if (!isMdx(uri)) {
+    return
```
Comment (remcohaszing) [inline packages/language-server/index.js:322]: I’m not sure how to test this. Explicitly no diagnostics should be sent, meaning we should basically assert a promise never resolves.

**Review by ChristianMurphy — APPROVED** [review]

File: packages/language-server/index.js (hunk 1 above)
Comment (remcohaszing) [reply packages/language-server/index.js:322]: I’ll get back to this when I add code coverage checks. For now I just really want to release these changes.
